[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "be818bf46626318e89858e06203fcec86e298883"
os = "macos"

    [[mimalloc.download]]
    sha256 = "54aa10bae0a06b90a347be45345f062ee90d366e86cd86389cef4e8d0cd369c2"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.aarch64-apple-darwin.tar.gz"
[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "035607db904f90eb441fd6feea2f0424791f22f4"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "7ac8449eabf30b22dd6a0ff62c7cedbbc9de80f904f19f06ac90435b40582024"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.aarch64-linux-gnu.tar.gz"
[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "bff90b5c0e4851b6ee8c6928987befcfbd46962e"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "ce6f9e99a2f68a57ce699fa9d303b653ed62afeec13b9d63a6f0644417125b53"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.aarch64-linux-musl.tar.gz"
[[mimalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2dc25d65fad0318d17ba1a912ebe48a170c97b96"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "f45838526239b3a9c0e91ae4ba1a0bec34cb42e4d8ad631640b014eb0e080d20"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.armv6l-linux-gnueabihf.tar.gz"
[[mimalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e39fe76fc4d19cee8264aa34367585d86035b67"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "6a6616229b3fa44457eba98e6564b3b4965ba1c253eefa0fcd6edb619842f93e"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.armv6l-linux-musleabihf.tar.gz"
[[mimalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "28dbc3da945da785fc56c9ed399c6ed1aa071b2f"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "7435bfee27d055f36ca5a8d92d38b6c8e4b9385abbd47a7f7593c77cc0c7d95e"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.armv7l-linux-gnueabihf.tar.gz"
[[mimalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "140327588e2ff9e190db477d84305c528e03fe4c"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "3feec61756010ae69dcde7cb2eaf70071062e24bdefb62e352d5f3d5fc8a820b"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.armv7l-linux-musleabihf.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "298c365e81b9a12493ce473e1cb6eeda051e7100"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "57da617b44f76c9c28534a5d7378c8f3256303506942b6cf70ee4d7927d66f6d"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.i686-linux-gnu.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "52ddd497b3000348c80c997852050478f1cbed3d"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "eb09e4356044631a3b5875a5df66dff86edda1e9773d888e7143ade3a56e3d21"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.i686-linux-musl.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "f74a9db0106c87c397fba66e328dc06bb3974198"
os = "windows"

    [[mimalloc.download]]
    sha256 = "f4f5f6bbfeac4b83bb02e4a010fc4ed592bbce6b76708cfbaa8d5665091522c6"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.i686-w64-mingw32.tar.gz"
[[mimalloc]]
arch = "powerpc64le"
git-tree-sha1 = "0d426f67b1da4f0143776aa62b34dc7b10b63a9d"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "6ab070812710ad9772c68fb8e6a9ed797ad16ce5495b9e237c94331399ff4688"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.powerpc64le-linux-gnu.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "5c88b29b8748b0e7e0941dc6da3abab55ea895a5"
os = "macos"

    [[mimalloc.download]]
    sha256 = "45af25b61776b4b763921b78c56f037627b3b0b80b484a42c7b5ce93b7b77b73"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.x86_64-apple-darwin.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "46cc719a4f55699fb4322b762be0479aec507eef"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "4261e6655c211722ecfc200b94b72a784ab395498b19f158101523bd03d26ee1"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.x86_64-linux-gnu.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "2cd15662ae27cbf901eb9f8776661f8c820eadcc"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "47f2ae95d609ada3a9f4fadebc8582bea3d237f632b920f814a8b37f8539e876"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.x86_64-linux-musl.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "4636205edea9d55880a4891887bf37ad6d41308f"
os = "freebsd"

    [[mimalloc.download]]
    sha256 = "b8318f2dae5cbad26819386d28cb3147206f903cb92930a5bb1e2927ec78f009"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.x86_64-unknown-freebsd.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "18d52812441a3f5252172e10a54c9f71a0a840aa"
os = "windows"

    [[mimalloc.download]]
    sha256 = "472ebfa519e4aa9595c359ab219f834ad28f337d7adc3bc26302486037d94b12"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.1.2+0/mimalloc.v2.1.2.x86_64-w64-mingw32.tar.gz"
