[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "6b1423c64b313bd889cc22d800fcae97597eb3cb"
os = "macos"

    [[mimalloc.download]]
    sha256 = "89571da90ff5906e201e0be6599489fe8f15cebed05461289859274a508063a9"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.aarch64-apple-darwin.tar.gz"
[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "fcc0edcc052d11855122f1cda741268b36b06178"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "2ff82fea76d099f56281dbb75f04e713342618d1a049526bbdfa246c6119b63b"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.aarch64-linux-gnu.tar.gz"
[[mimalloc]]
arch = "aarch64"
git-tree-sha1 = "db1a8fee7551ec70f1d14a5351e067ec5666f307"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "5a00ef4f6237d97a639392219b8edeb265960cc9c1639d847d8b6dd044febd1b"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.aarch64-linux-musl.tar.gz"
[[mimalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eed37441b8937c6a428629591d66a1b994c23760"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "a4b9908f8085923593dcf3a928f85c7b4b8aa39cc2e70b8ddc32ce9ee4ddaeff"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.armv6l-linux-gnueabihf.tar.gz"
[[mimalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e7da616e49626779cf056fd60b2cd668dc1d994"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "9ec1f5678fa2fa43fdfef6a0f18e8c9f4a2162e18c933e0c45615d7a68156c3f"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.armv6l-linux-musleabihf.tar.gz"
[[mimalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7243d282f6836d672c23cd505022edcd00f67cd"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "75b5e3a537dff368572f3c55220e0a4c4ff18b2008f268a2e1d6599f681d10bc"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.armv7l-linux-gnueabihf.tar.gz"
[[mimalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f630016795c568b4236bfdf6cc9bafea5db6938"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "0f4df5f24a9df69ee4078e6de974f88b9ac327ec11f46d813494ac59d578cd2d"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.armv7l-linux-musleabihf.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "e1fb548d1bb93420f9202db716b2ac13c47c33c7"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "900100ce51cd0206f445e0976e6ad15058ad9aac5d5887b87f6f75019c794319"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.i686-linux-gnu.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "3571c7d2f7cfc7d2958183a454f731c06f3b8456"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "9f810cda07c1d8c6234cad0ea5fb623d13cbebf9ba4bef425158fe7df0ef1700"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.i686-linux-musl.tar.gz"
[[mimalloc]]
arch = "i686"
git-tree-sha1 = "8663dc4497b3db970d679956376f2ba8ea2a51fb"
os = "windows"

    [[mimalloc.download]]
    sha256 = "2e107124c874579d4233c91226507f068d7ec84475c25e0c3cbeac0c61b0a240"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.i686-w64-mingw32.tar.gz"
[[mimalloc]]
arch = "powerpc64le"
git-tree-sha1 = "9e56c6b943c04d84ee281e96e12e8736b3006d40"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "aba5bdd80720aae1364d57672c95ff5883c1b0ac16b9fd0b2a95e5f84f9c47f4"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.powerpc64le-linux-gnu.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "fe939a35521ee774575070aef7bb07390865b590"
os = "macos"

    [[mimalloc.download]]
    sha256 = "8c00a0ec110068e5351a33991c0e7be09a9ad285730352cff779564a03a971eb"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.x86_64-apple-darwin.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "1473c605c9c689af582d9592e3883c3eb216dbe9"
libc = "glibc"
os = "linux"

    [[mimalloc.download]]
    sha256 = "035607052340c790147464b6a9bbcf62e9eb28832b492a09f25db24bc8c1e277"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.x86_64-linux-gnu.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "a686d4ab47f63c96600871321525a791ffc62efd"
libc = "musl"
os = "linux"

    [[mimalloc.download]]
    sha256 = "ad76920d674dd682b0274a3dfefba35651bed98a21884c5b0ad7575019497afa"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.x86_64-linux-musl.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "db8fedd2fb9531031ae7f4b734a58696788fe475"
os = "freebsd"

    [[mimalloc.download]]
    sha256 = "e188e95aaa00784f42099da4519e4a8539f0867aeaf8763eef790ee4f7b78ccc"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.x86_64-unknown-freebsd.tar.gz"
[[mimalloc]]
arch = "x86_64"
git-tree-sha1 = "1a8357724d11913844cc350075e13ba5fb841609"
os = "windows"

    [[mimalloc.download]]
    sha256 = "8b7a04adf3136293f3356e6c476d895b1ef8e839508e5c2e5f3c59333969f53c"
    url = "https://github.com/JuliaBinaryWrappers/mimalloc_jll.jl/releases/download/mimalloc-v2.0.6+0/mimalloc.v2.0.6.x86_64-w64-mingw32.tar.gz"
